/* strings-es.jsx — Spanish copy. window.STRINGS.es */
window.STRINGS = window.STRINGS || {};
window.STRINGS.es = {
  langName: "Español", otherLang: "English",
  presets: {
    insurance_storm: { eyebrow: "Daños por tormenta y monzón", headline: "¿Daños por tormenta o monzón? Puede calificar para un techo nuevo a través de su seguro.", subhead: "Nuestros profesionales verificados en Arizona se encargan de la inspección y del papeleo del reclamo con usted. Vea si su techo califica en unos 2 minutos.", cta: "Ver si mi techo califica" },
    free_inspection: { eyebrow: "Techos en Arizona", headline: "Inspección de techo gratis en Arizona. Sepa exactamente en qué situación está.", subhead: "Un profesional local verificado revisa su techo de arriba a abajo y le dice la verdad: reparar, reemplazar o dejarlo así. Sin presión, sin spam.", cta: "Agendar mi inspección gratis" },
    qualify_quiz: { eyebrow: "¿Su techo califica?", headline: "¿Su techo en Arizona necesita reemplazo? Averígüelo en 2 minutos.", subhead: "Responda unas preguntas rápidas. Lo conectamos con el especialista verificado correcto para su techo: teja, espuma o asfalto.", cta: "Ver si mi techo califica" },
    zero_down: { eyebrow: "Techos en Arizona, $0 de enganche", headline: "Un techo nuevo en Arizona por $0 de enganche. Pague mensual, adelántese al monzón.", subhead: "Lo conectamos con un profesional local verificado y un pago que le acomode. Cotización gratis, sin presión, sin spam.", cta: "Recibir mi cotización" },
    free_quote: { eyebrow: "Techos en Arizona, resuelto", headline: "Su cotización de techo gratis en Arizona, rápido.", subhead: "Cuéntenos sobre su techo y lo conectamos con un profesional local verificado. Cotización gratis, sin presión, sin spam.", cta: "Recibir mi cotización gratis" },
  },
  monsoon: { eyebrow: "Antes del próximo monzón", headline: "Prepárese para el monzón antes de la próxima tormenta en el Valle.", cta: "Prepararme para el monzón" },
  hero: { micro: "Toma unos 2 minutos", photoTag: "FOTO DE CASA EN ARIZONA" },
  trust: {
    licensed: "Profesionales de Arizona con licencia y registro ROC", local: "Equipos locales de Arizona", free: "Cotización gratis y sin compromiso", spam: "Nunca le enviamos spam. Jamás.",
    licensedShort: "Con licencia", localShort: "Equipos locales", freeShort: "Cotización gratis", spamShort: "Sin spam, jamás",
  },
  exclus: {
    dealsH: "Ofertas que no encontrará en ningún otro lado.",
    dealsBody: "Como verificamos a cada propietario en nuestra red, los proveedores confiables de Arizona confían en esta audiencia lo suficiente como para ofrecer precios que mantienen fuera del mercado público. La verificación es lo que desbloquea las ofertas.",
    dealsTie: "Las verá en cuanto su llamada esté agendada.",
    dealsVault: "Ofertas exclusivas de la red",
    dealsExamplesH: "Ejemplos de lo que llega",
    dealsExamples: [
      { icon: "ph-sun", label: "Solar sin enganche", sub: "Financiamiento que ofrecen primero nuestros instaladores." },
      { icon: "ph-grid-nine", label: "Ventanas cubiertas por el seguro", sub: "De bajo consumo, a menudo cubiertas por su póliza." },
      { icon: "ph-wind", label: "Precios de mantenimiento de aire", sub: "Tarifas antes del verano, antes de la temporada alta." },
      { icon: "ph-house-line", label: "Tarifas de techo fuera de temporada", sub: "Reparaciones y reemplazos a precio de meses tranquilos." },
    ],
    vettedH: "Verificado en ambos sentidos.",
    vettedSub: "Sea bueno con nuestra gente, y nos aseguraremos de que nuestra gente sea buena con usted.",
    prosH: "Cómo nuestros profesionales se ganan su lugar",
    pros: ["Con licencia y registrados en Arizona", "Asegurados, con historial y reseñas reales", "Asignados al especialista correcto para usted", "Conocidos por llegar y respaldar su trabajo"],
    askH: "Lo que pedimos a los propietarios",
    ask: ["Una casa real y un proyecto real para cotizar", "Que cumpla las citas que agenda con nosotros", "Abierto a una llamada rápida y sin presión", "Trato directo y respetuoso, en ambas direcciones"],
    closer: "Ese equilibrio es exactamente por lo que las ofertas siguen siendo exclusivas y los profesionales siguen respondiendo. Cumpla su parte y seguiremos enviándole las mejores ofertas de Arizona.",
    brandSeed: "Techos hoy. Lo que la casa necesite después.",
  },
  how: { eyebrow: "Cómo funciona", h: "Tres toques para una cotización real.", steps: {
    s1: { head: "Cuéntenos sobre su techo", body: "Unos toques rápidos. Sin formularios complicados." },
    s2: { head: "Lo conectamos con un profesional verificado", body: "Una red local pequeña que revisamos personalmente." },
    s3: { head: "Cotización gratis y llamada en 2 minutos", body: "Un especialista real de Arizona, en la línea rápido." } } },
  stats: { rating: "Calificación promedio de propietarios", matched: "Propietarios del Valle conectados", speed: "Para hablar con un especialista" },
  testimonials: [
    { quote: "Llené un solo formulario esperando que mi teléfono no parara de sonar. En vez de eso, una sola persona me llamó, sabía todo sobre techos de teja, y fue mi contacto de principio a fin. Nunca me pasaron de un lado a otro.", name: "Dale W.", city: "Mesa, AZ" },
    { quote: "Me conectaron con un equipo que de verdad entendía los techos de espuma en este calor, no con una empresa de otro estado. Se nota que solo trabajan con gente que conoce Arizona.", name: "Marisol R.", city: "Gilbert, AZ" },
    { quote: "Mi profesional me dijo que a mi techo le quedaban cinco buenos años en lugar de venderme uno nuevo. Ahí supe que estaban de mi lado. Se sintió como tener un amigo en el negocio.", name: "Priya N.", city: "Chandler, AZ" },
    { quote: "Una vez usé un directorio grande y recibí veinte llamadas en un día. Con ellos fue una llamada, un profesional, listo. Como del cielo a la tierra.", name: "Ramon T.", city: "Surprise, AZ" },
  ],
  concierge: { h: "Por qué un concierge, no un directorio.", body: "Los directorios venden su número a veinte empresas y las dejan pelear por usted. Nosotros no. Mantenemos una red pequeña y verificada de profesionales de Arizona y lo conectamos a mano con uno que hace su tipo de techo.", cardH: "Lo que eso significa para usted", points: ["Un especialista, no un menú de opciones", "Equipos locales con licencia y verificados", "Su información nunca se revende"] },
  footer: { meta: "Profesionales locales con licencia · Expansión en Estados Unidos", privacy: "Política de privacidad", terms: "Términos", fine: "Somos un servicio de referencia que conecta a propietarios con proveedores de servicios locales e independientes. Nunca vendemos ni enviamos spam con su información. © 2026 Casa Concierge.",
    disclaimerNote: "Divulgación legal importante",
    disclaimerShort: "Casa Concierge es un servicio de referencia en Estados Unidos que conecta a propietarios con proveedores de servicios locales e independientes. No somos un contratista con licencia y no estamos afiliados ni respaldados por Meta, Google ni ninguna otra plataforma. Todas las marcas pertenecen a sus respectivos dueños. No vendemos su información personal. Las ofertas, la disponibilidad y los resultados varían según el mercado y no están garantizados. © 2026 Casa Concierge. Todos los derechos reservados." },
  form: {
    back: "Volver", continue: "Continuar", continueAnyway: "Continuar de todos modos",
    foot: "Seguro y privado · Nunca vendemos su información",
    smsOptInLabel: "Sí, doy mi consentimiento para ser contactado",
    steps: {
      need: { q: "¿Qué necesita su techo?", why: "Para conectarlo con un profesional que haga exactamente este tipo de trabajo.", options: { replace: "Reemplazar mi techo", repair: "Reparar un problema", inspect: "Inspección gratis", explore: "Solo explorando" } },
      material: { q: "¿Qué tipo de techo tiene?", why: "Los techos en Arizona son especializados, así que esto le consigue al especialista correcto, no a un generalista.", options: { tile: "Teja", shingle: "Asfalto (shingle)", foam: "Espuma / Plano", metal: "Metal", unsure: "No estoy seguro" } },
      condition: { q: "¿Cómo está aguantando?", why: "Nos dice si enviar a alguien esta semana o solo conseguirle una cotización.", options: { leaking: "Tiene goteras ahora", damage: "Daño visible", aging: "Viejo, planeando con tiempo" } },
      owner: { q: "¿Es dueño de la casa?", why: "Solo cotizamos a propietarios, así que su lugar queda reservado para proyectos reales.", options: { own: "Sí, soy el dueño", rent: "Rento" } },
      address: { q: "¿Dónde está la casa?", why: "Para que su profesional revise detalles de HOA y permisos y cotice con precisión, sin adivinar.", label: "Dirección de la casa", placeholder: "Empiece a escribir su dirección", found: "Encontramos su casa.", loading: "Buscando direcciones...", fallback: "La búsqueda en vivo no está disponible ahora, así que mostramos sugerencias de respaldo." },
      name: { q: "¿Por quién debe preguntar nuestro especialista?", why: "Para saber a quién llamamos. Queda con nosotros, nunca con un centro de llamadas.", first: "Nombre", last: "Apellido" },
      contact: { q: "¿Cuál es el mejor número para su llamada en 2 minutos?", phoneLabel: "Número de celular", phonePlaceholder: "(480) 555-0123", submit: "Recibir mi cotización gratis", hint: "Agregue su número para continuar." },
    },
    renter: { strong: "Aviso: las cotizaciones de techo son para propietarios.", body: "No hay problema si renta. Siga y le conseguiremos servicios que sí puede usar, como control de plagas y alarmas." },
    antispam: { lead: "La mayoría de los sitios venden su información a los spammers.", emphasis: "Nosotros no.", tail: "Usted habla con nosotros, y solo con los profesionales que pida." },
    requestConsent: "Al hacer clic en \"{cta}\", acepto que Casa Concierge, operado por Scaling Adventures, LLC, pueda llamarme o enviarme mensajes de texto al número que proporcioné para programar, confirmar, coordinar y dar seguimiento a esta solicitud de inspección de techo.",
    requestConsentMeta: "Nuestro equipo usa esta información de contacto solo para ayudar con la inspección que usted pidió.",
    tcpa: "Acepto recibir llamadas y mensajes de texto conversacionales, transaccionales y promocionales de Casa Concierge, operado por Scaling Adventures, LLC, sobre esta solicitud y servicios relacionados, incluidos mensajes enviados con tecnología automatizada.",
    tcpaMeta: "La frecuencia de los mensajes varía. Pueden aplicarse tarifas de mensajes y datos. Responda STOP para cancelar o HELP para obtener ayuda. El consentimiento no es una condición de compra. Esta casilla es opcional.",
  },
  processing: { title: "Preparando su llamada", items: { match: "Conectándolo con un especialista verificado de Arizona", confirm: "Confirmando que un profesional cubre {city}", reserve: "Reservando su llamada de 2 minutos" }, foot: "Buscando profesionales cerca de usted en el Valle" },
  ty: {
    qualify: "Buenas noticias, es probable que su techo califique", youreIn: "Ya quedó",
    h: "Le llamaremos ahora.", callfrom: "Desde {phone}. Tenga su teléfono a la mano.", ringLabel: "para su llamada",
    expiredH: "Puede que nuestro equipo esté en otra llamada. Mejor llámenos usted ahora.", callNow: "Llámenos ahora",
    narrEyebrow: "Último paso antes de llamarle",
    narrTitle: "Explore ofertas exclusivas de nuestros proveedores locales verificados",
    narrSub: "En el area de Phoenix",
    narrSubDetail: "Seleccione cualquier oferta adicional sobre la que quiera recibir informacion en nuestra llamada.",
    wallHeadOwner: "Ofertas adicionales", wallHeadRenter: "Ofertas adicionales", tapToAdd: "Toque para agregar",
    toggleAdd: "Me interesa saber más", toggleAdded: "Agregado",
    ctaZero: "Confirmar mi llamada en 2 minutos", ctaN: "Hablar de estas {n} ofertas en la llamada", skip: "Solo el techo por ahora",
    emailPlaceholder: "correo@ejemplo.com", emailBtn: "Enviarme ofertas", emailDone: "Listo. Revise su correo.",
    emailStepH: "Su solicitud ya está enviada. ¿Quiere también nuestras ofertas de temporada de Arizona por correo?", emailStepSub: "Su solicitud de techo ya está enviada. Esto es solo un extra.", emailSkip: "Omitir",
    offersOwner: {
      solar: { eyebrow: "Reduzca su factura de APS/SRP hasta 90%", head: "Solar con $0 de enganche", benefit: "Nada de su bolsillo para empezar." },
      windows: { eyebrow: "Ventanas nuevas, a menudo $0 de su bolsillo", head: "Ventanas cubiertas por el seguro", benefit: "De bajo consumo, a menudo cubiertas por el seguro." },
      hvac: { eyebrow: "Véngale al calor de Arizona antes de que suba", head: "Mantenimiento y reemplazo de aire acondicionado", benefit: "Revisión gratis del aire antes del verano." },
      pest: { eyebrow: "Mantenga los escorpiones fuera para siempre", head: "Control de escorpiones y plagas", benefit: "Tarifa especial para propietarios." },
      gutters: { eyebrow: "Proteja su casa del monzón", head: "Canaletas sin uniones", benefit: "Canaletas y protectores de hojas." },
      landscape: { eyebrow: "Baje su factura de agua, olvide el mantenimiento", head: "Jardinería desértica de bajo consumo de agua", benefit: "Renovación ahorradora y césped artificial." },
      windowcleaning: { eyebrow: "Vidrios impecables, sin escalera", head: "Limpieza profesional de ventanas", benefit: "Una vez o de forma recurrente." },
    },
    offersRenter: {
      pest: { eyebrow: "Mantenga los escorpiones fuera para siempre", head: "Control de escorpiones y plagas", benefit: "Planes para inquilinos." },
      alarms: { eyebrow: "Protección que se muda con usted", head: "Seguridad y monitoreo del hogar", benefit: "Alarma inteligente sin perforar." },
      hvac: { eyebrow: "Manténgase fresco en el pico del verano", head: "Mantenimiento de aire acondicionado", benefit: "Revisión gratis del aire." },
      windowcleaning: { eyebrow: "Vidrios impecables, sin escalera", head: "Limpieza profesional de ventanas", benefit: "Una vez o de forma recurrente." },
      housecleaning: { eyebrow: "Llegue a casa y encuentre todo en orden", head: "Limpieza del hogar", benefit: "Limpiezas únicas o recurrentes." },
      plumbing: { eyebrow: "Arregle fugas antes de que den más problemas", head: "Ayuda de plomería", benefit: "Programación rápida para reparaciones comunes." },
    },
  },
  confirmed: { h: "Todo listo. Hablamos pronto.", bodyA: "Su especialista tiene su solicitud de techo", bodyPlus: "más {n} {svc} para cubrir", svc1: "servicio", svcN: "servicios", bodyB: "Esté pendiente de una llamada desde {phone}.", restart: "Empezar de nuevo",
    nextH: "Qué sigue", next: ["Hable con un asesor de servicios para el hogar de verdad", "Asegure su cita para el techo", "Vea para qué ofertas exclusivas califica"],
    saveH: "Guarde el contacto de su nuevo asesor del hogar.", saveSub: "Agréguenos a sus contactos para que pueda encontrarnos cuando nos necesite.", saveBtn: "Guardar contacto" },
};
