/* strings-home-es.jsx — homepage copy (augments STRINGS.es.home) */
window.STRINGS = window.STRINGS || {}; window.STRINGS.es = window.STRINGS.es || {};
window.STRINGS.es.home = {
  nav: { services: "Servicios", howWeVet: "Cómo verificamos", areas: "Áreas de servicio", reviews: "Reseñas", about: "Nosotros", contact: "Contacto", quote: "Cotización gratis", forPros: "Para profesionales" },
  hero: {
    eyebrow: "Concierge para el hogar en Arizona",
    pill: "Ahora servimos el área metropolitana de Phoenix — y creciendo rápido.",
    h: "Su concierge del hogar para cada proyecto, reparación y mejora.",
    sub: "Cuéntenos qué necesita la casa. Nosotros alineamos profesionales locales verificados, mantenemos el proceso simple y compartimos las ofertas que nuestra red recibe primero.",
    highlights: [
      "Un solo contacto de confianza desde la cotización hasta la llamada",
      "Profesionales verificados de Arizona, nunca una subasta al azar",
      "Ofertas exclusivas para propietarios, sin spam",
    ],
    ctaPrimary: "Encuentre su servicio", ctaSecondary: "Quiero las ofertas",
  },
  servicesH: "¿Qué necesita su casa?",
  servicesSub: "Elija un servicio. Lo conectamos con un profesional verificado de Arizona que hace exactamente ese trabajo.",
  liveBadge: "Cotización gratis", soonBadge: "Unirme a la lista",
  getStarted: "Comenzar",
  moreH: "Más servicios para el hogar",
  moreShow: "Ver todos los servicios", moreHide: "Ver menos",
  services: [
    { id: "roofing", icon: "ph-house-line", eyebrow: "Cotización en unos 2 minutos", name: "Techos", desc: "Reparar, reemplazar o inspección gratis. Teja, espuma, asfalto.", page: "Roofing.html" },
    { id: "solar", icon: "ph-sun", eyebrow: "Reduzca su factura hasta 90%", name: "Solar", desc: "Opciones de $0 de enganche. Pague mensual.", page: "/solar" },
    { id: "hvac", icon: "ph-wind", eyebrow: "Véngale al calor de Arizona", name: "Aire acondicionado", desc: "Mantenimiento, reparación y reemplazo antes del pico.", page: "/ac-hvac" },
    { id: "windows", icon: "ph-grid-nine", eyebrow: "A menudo $0 con su cobertura", name: "Ventanas", desc: "Ventanas de bajo consumo, a menudo cubiertas por el seguro.", page: "/windows" },
    { id: "bathroom", icon: "ph-bathtub", eyebrow: "Mejoras estilo spa, rápido", name: "Remodelación de baño", desc: "Duchas, tinas, tocadores y azulejo.", page: "/bathroom-remodel" },
    { id: "kitchen", icon: "ph-cooking-pot", eyebrow: "Cocine en una cocina que ame", name: "Remodelación de cocina", desc: "Gabinetes, encimeras y renovación completa.", page: "/kitchen-remodel" },
    { id: "pool", icon: "ph-swimming-pool", eyebrow: "Su patio, véngale al calor", name: "Piscina", desc: "Construcción, remodelación y resurfacing.", page: "/pool" },
    { id: "pest", icon: "ph-bug-beetle", eyebrow: "Mantenga fuera los escorpiones", name: "Control de plagas y escorpiones", desc: "Planes para propietarios e inquilinos.", page: "/pest-control" },
  ],
  moreServices: [
    { id: "gutters", icon: "ph-cloud-rain", name: "Canaletas", page: "/gutters" },
    { id: "siding", icon: "ph-house-simple", name: "Revestimiento", page: "/siding" },
    { id: "garage", icon: "ph-door", name: "Puertas de garaje", page: "/garage-doors" },
    { id: "foundation", icon: "ph-stack", name: "Reparación de cimientos", page: "/foundation-repair" },
    { id: "insulation", icon: "ph-thermometer", name: "Aislamiento", page: "/insulation" },
    { id: "poolservice", icon: "ph-drop", name: "Servicio de piscina", page: "/pool-service" },
    { id: "landscape", icon: "ph-plant", name: "Jardinería desértica", page: "/desert-landscaping" },
    { id: "tree", icon: "ph-tree", name: "Servicio de árboles", page: "/tree-service" },
    { id: "plumbing", icon: "ph-wrench", name: "Plomería", page: "/plumbing" },
    { id: "electrical", icon: "ph-lightning", name: "Electricidad", page: "/electrical" },
    { id: "water", icon: "ph-flask", name: "Tratamiento de agua", page: "/water-treatment" },
    { id: "alarms", icon: "ph-shield-check", name: "Seguridad del hogar", page: "/home-security" },
    { id: "flooring", icon: "ph-squares-four", name: "Pisos", page: "/flooring" },
    { id: "painting", icon: "ph-paint-roller", name: "Pintura", page: "/painting" },
    { id: "epoxy", icon: "ph-paint-bucket", name: "Epóxico de garaje", page: "/garage-epoxy" },
    { id: "housecleaning", icon: "ph-broom", name: "Limpieza de casa", page: "/house-cleaning" },
    { id: "windowcleaning", icon: "ph-sparkle", name: "Limpieza de ventanas", page: "/window-cleaning" },
  ],
  how: {
    eyebrow: "Cómo funciona",
    h: "Un concierge para toda su casa.",
    steps: [
      { icon: "ph-house", head: "Cuéntenos qué necesita su casa", body: "Techos hoy, lo que venga después. Unos toques rápidos." },
      { icon: "ph-users-three", head: "Lo conectamos con un profesional verificado", body: "Una red pequeña que revisamos por licencia, seguro e historial." },
      { icon: "ph-phone-call", head: "Un solo contacto. Cotización gratis. Sin spam.", body: "Usted habla con nosotros, y solo con los profesionales que pida." },
    ],
  },
  areas: {
    eyebrow: "Locales del Valle",
    h: "Ahora servimos el área metropolitana de Phoenix — y creciendo rápido.",
    sub: "Equipos que conocen los techos, el calor y los monzones de Arizona.",
    cities: ["Phoenix", "Mesa", "Gilbert", "Chandler", "Scottsdale", "Tempe", "Glendale", "Peoria", "Surprise"],
  },
  deals: {
    eyebrow: "Ofertas exclusivas",
    h: "Reciba las ofertas que nuestra red ve primero.",
    sub: "Ofertas de temporada de Arizona que mantenemos fuera del mercado público, solo para nuestros propietarios. Sin spam, cancele cuando quiera.",
    emailPlaceholder: "correo@ejemplo.com", btn: "Unirme a la lista",
    done: "Ya está en la lista. Revise su correo para las mejores ofertas de Arizona.",
    save: "O guarde nuestro número",
  },
  about: {
    eyebrow: "Por qué empezamos esto",
    h: "Queríamos una mejor forma de contratar profesionales del hogar.",
    body: "Casa Concierge es un pequeño equipo de Arizona que se hartó de ver a sus vecinos atrapados entre devoluciones de llamada al azar y cotizaciones confusas. Así que construimos lo contrario: una red verificada, un solo contacto real y ofertas que se ganan siendo fácil de tratar.",
    cta: "Lea nuestra historia",
  },
  faq: {
    eyebrow: "Preguntas",
    h: "Buenas preguntas, respuestas claras.",
    items: [
      { q: "¿Ustedes son el contratista?", a: "No. Somos un servicio de referencia que lo conecta con profesionales de Arizona con licencia y registro ROC. No somos un contratista con licencia." },
      { q: "¿Mi teléfono se llenará de spam?", a: "No. Nunca subastamos su número. Usted habla con nosotros, y solo con los profesionales que pida." },
      { q: "¿Cuánto cuesta?", a: "Nada por conectarlo y cotizar. Las cotizaciones son gratis y sin compromiso." },
      { q: "¿Qué áreas cubren?", a: "El área metropolitana de Phoenix, desde Surprise hasta Gilbert y todo lo que hay en medio." },
    ],
    cta: "Ver todas las preguntas",
  },
  footer: {
    tagline: "Su concierge de servicios para el hogar en Arizona. Un solo contacto de confianza para toda la casa.",
    company: "Empresa", servicesCol: "Servicios", areasCol: "Áreas de servicio", legal: "Legal",
    links: {
      about: "Nosotros", howWeVet: "Cómo verificamos", contact: "Contacto", reviews: "Reseñas", faq: "Preguntas", blog: "Blog",
      privacy: "Política de privacidad", terms: "Términos", tcpa: "TCPA y consentimiento", cookies: "Política de cookies", accessibility: "Accesibilidad", guarantee: "Nuestra garantía",
    },
    roc: "Trabajamos con proveedores locales e independientes y verificamos los requisitos aplicables según el servicio y el mercado.",
    addr: "30 N Gould St Ste R, Sheridan, WY 82801",
    fine: "Somos un servicio de referencia, no un contratista con licencia. Nunca vendemos ni enviamos spam con su información. © 2026 Casa Concierge.",
    contact: "hello@textcasaconcierge.com",
    disclaimerNote: "Divulgación legal importante",
    disclaimer: "Scaling Adventures, LLC opera comercialmente como Casa Concierge. Casa Concierge es un servicio de referencia que conecta a propietarios con proveedores de servicios locales e independientes. No somos un contratista con licencia y no realizamos trabajos de mejoras para el hogar nosotros mismos. No estamos afiliados, ni respaldados ni patrocinados por Meta Platforms, Inc. (Facebook, Instagram), Google ni ninguna otra plataforma. Todas las marcas son propiedad de sus respectivos dueños. No vendemos su información personal a terceros para su propio marketing. Lo conectamos únicamente con los proveedores que solicita. Los ahorros, ofertas y resultados varían y no están garantizados. La disponibilidad de proveedores, los requisitos de licencia y las áreas de servicio varían según el mercado. Al enviar una solicitud acepta nuestra Política de Privacidad, Términos de Servicio y ser contactado según se describe en nuestros términos de consentimiento. © 2026 Casa Concierge. Todos los derechos reservados.",
    disclaimerShort: "Casa Concierge es un servicio de referencia en Estados Unidos que conecta a propietarios con proveedores de servicios locales e independientes. No somos un contratista con licencia y no estamos afiliados ni respaldados por Meta, Google ni ninguna otra plataforma. Todas las marcas pertenecen a sus respectivos dueños. No vendemos su información personal. Las ofertas, la disponibilidad y los resultados varían según el mercado y no están garantizados. © 2026 Casa Concierge. Todos los derechos reservados.",
  },
};
