/* strings-en.jsx — English copy. window.STRINGS.en */
window.STRINGS = window.STRINGS || {};
window.STRINGS.en = {
  langName: "English", otherLang: "Español",
  presets: {
    insurance_storm: { eyebrow: "Monsoon & storm damage", headline: "Storm or monsoon damage? You may qualify for a new roof through your insurance.", subhead: "Our vetted Arizona pros handle the inspection and the claim paperwork with you. See if your roof qualifies in about 2 minutes.", cta: "See if my roof qualifies" },
    free_inspection: { eyebrow: "Arizona roofing", headline: "Get a Free Roof Inspection", subhead: "Let a vetted local roofer inspect your roof top to bottom, then tells you straight: repair, replace, or leave it. No pressure, no spam, no obligation.", cta: "Book my free inspection" },
    qualify_quiz: { eyebrow: "Does your roof qualify?", headline: "Is your Arizona roof due for replacement? Find out in 2 minutes.", subhead: "Answer a few quick questions. We match you with the right vetted specialist for your roof: tile, foam, or shingle.", cta: "Check if my roof qualifies" },
    zero_down: { eyebrow: "Arizona roofing, $0 down", headline: "A new Arizona roof for $0 down. Pay monthly, beat the next monsoon.", subhead: "Get matched with a vetted local pro and a payment that fits. Free quote, no pressure, no spam.", cta: "Get my $0-down quote" },
    free_quote: { eyebrow: "Arizona roofing, handled", headline: "Your free Arizona roof quote, fast.", subhead: "Tell us about your roof and we will match you with a vetted local pro. Free quote, no pressure, no spam.", cta: "Get my free roof quote" },
  },
  monsoon: { eyebrow: "Before the next monsoon", headline: "Get monsoon-ready before the next storm hits the Valley.", cta: "Get monsoon-ready" },
  hero: { micro: "Takes about 2 minutes", photoTag: "ARIZONA HOME PHOTO" },
  trust: {
    licensed: "Licensed, ROC-registered Arizona pros", local: "Local Arizona crews", free: "Free, no-obligation quote", spam: "We never spam you. Ever.",
    licensedShort: "Licensed pros", localShort: "Local AZ crews", freeShort: "Free quote", spamShort: "No spam, ever",
  },
  exclus: {
    dealsH: "Deals you can't find anywhere else.",
    dealsBody: "Because we vet every homeowner in our network, reputable Arizona providers trust this audience enough to extend offers they keep off the public market. The vetting is what unlocks the deals.",
    dealsTie: "You'll see them the moment your call is set.",
    dealsVault: "Exclusive network offers",
    dealsExamplesH: "Examples of what comes through",
    dealsExamples: [
      { icon: "ph-sun", label: "$0-down solar", sub: "Financing our installers extend first." },
      { icon: "ph-grid-nine", label: "Insurance-covered windows", sub: "Energy-efficient, often covered by your policy." },
      { icon: "ph-wind", label: "Seasonal HVAC tune-up pricing", sub: "Pre-summer rates, before the rush." },
      { icon: "ph-house-line", label: "Off-season roofing rates", sub: "Repairs and replacements at quieter-month pricing." },
    ],
    vettedH: "Vetted both ways.",
    vettedSub: "Be good to our people, and we'll make sure our people are good to you.",
    prosH: "How our pros earn their spot",
    pros: ["Licensed and ROC-registered in Arizona", "Insured, with verified reviews and a track record", "Matched to the right specialist, not whoever's free", "Known to show up and stand behind the work"],
    askH: "What we ask of homeowners",
    ask: ["A real home and a real project to quote", "You keep the appointments you book with us", "Open to a quick, no-pressure phone call", "Straightforward and respectful, both directions"],
    closer: "That balance is exactly why the deals stay exclusive and the pros stay responsive. Hold up your end and we'll continue sending you Arizona's best deals.",
    brandSeed: "Roofing today. Whatever the house needs next.",
  },
  how: { eyebrow: "How it works", h: "Three taps to a real quote.", steps: {
    s1: { head: "Tell us about your roof", body: "A few quick taps. No forms to wrestle with." },
    s2: { head: "We match you with a vetted pro", body: "A small, local network we have personally screened." },
    s3: { head: "Free quote and 2-minute callback", body: "A real Arizona specialist, on the line fast." } } },
  stats: { rating: "Average homeowner rating", matched: "Valley homeowners matched", speed: "To a real Arizona specialist" },
  testimonials: [
    { quote: "I filled out one form expecting my phone to blow up. Instead one person called, knew tile roofs cold, and stayed my contact the whole way through. Never got passed around.", name: "Dale W.", city: "Mesa, AZ" },
    { quote: "They matched me with a crew that actually understood foam roofs in this heat, not some out-of-state outfit. You can tell they only work with people who know Arizona.", name: "Marisol R.", city: "Gilbert, AZ" },
    { quote: "My guy told me my roof had five good years left instead of selling me a new one. That is when I knew they were on my side. Felt like having a friend in the business.", name: "Priya N.", city: "Chandler, AZ" },
    { quote: "Used a big directory once and got twenty calls in a day. With these folks it was one call, one pro, done. Night and day.", name: "Ramon T.", city: "Surprise, AZ" },
  ],
  concierge: { h: "Why a concierge, not a directory.", body: "Directories sell your number to twenty companies and let them fight over you. We don't. We keep a small, vetted network of Arizona pros and hand-match you to one who does your kind of roof.", cardH: "What that means for you", points: ["One specialist, not a phone tree", "Screened, licensed local crews", "Your info is never resold"] },
  footer: { meta: "Licensed local pros · Expanding across the United States", privacy: "Privacy Policy", terms: "Terms", fine: "We are a referral service that connects homeowners with independent local service providers. We never sell or spam your information. © 2026 Vetted Local Providers.",
    disclaimerNote: "Important legal disclosure",
    disclaimerShort: "Vetted Local Providers is a U.S. lead-referral service connecting homeowners with independent local service providers. We are not a licensed contractor and are not affiliated with or endorsed by Meta, Google, or any other platform. All trademarks belong to their respective owners. We do not sell your personal information. Offers, availability, and results vary by market and are not guaranteed. © 2026 Vetted Local Providers. All rights reserved." },
  form: {
    back: "Go back", continue: "Continue", continueAnyway: "Continue anyway",
    foot: "Secure and private · We never sell your info",
    smsOptInLabel: "Consent to Contact",
    steps: {
      need: { q: "What does your roof need?", why: "So we match you with a pro who does exactly this kind of work.", options: { replace: "Replace my roof", repair: "Repair a problem", inspect: "Free inspection", explore: "Just exploring" } },
      material: { q: "What kind of roof do you have?", why: "Arizona roofs are specialized, so this gets you the right specialist, not a generalist.", options: { tile: "Tile", shingle: "Shingle", foam: "Foam / Flat", metal: "Metal", unsure: "Not sure" } },
      condition: { q: "How is it holding up?", why: "Tells us whether to send someone this week or just get you a quote.", options: { leaking: "It is leaking now", damage: "Some visible damage", aging: "Aging, planning ahead" } },
      owner: { q: "Do you own the home?", why: "We only quote homeowners, so your spot stays reserved for real projects.", options: { own: "Yes, I own it", rent: "I rent" } },
      address: { q: "Where is the home?", why: "So your pro can pull HOA and permit details and quote accurately, not guess.", label: "Home address", placeholder: "Start typing your address", found: "We found your home.", loading: "Looking up addresses...", fallback: "Live lookup is unavailable right now, so showing backup suggestions instead." },
      name: { q: "Who should our specialist ask for?", why: "So we know who we are calling. It stays with us, never a call center.", first: "First name", last: "Last name" },
      contact: { q: "Best number for your 2-minute callback?", phoneLabel: "Mobile number", phonePlaceholder: "(480) 555-0123", submit: "Get my free quote", hint: "Add your number to continue. SMS consent is not required." },
    },
    renter: { strong: "Heads up, roof quotes are for homeowners.", body: "No problem if you rent. Keep going and we will line up services you can use, like pest control and alarms." },
    antispam: { lead: "Most sites sell your info to spammers.", emphasis: "We don't.", tail: "You talk to us, and only the pros you ask for." },
    tcpa: "By checking this box and clicking \"{cta}\", I agree to receive calls and text messages from Vetted Local Providers, operated by Scaling Adventures, LLC, at the number I provided about my quote request, appointment scheduling, follow-up, requested provider coordination, and the related services I ask about, including messages sent with automated technology.",
    tcpaMeta: "Message frequency varies. Message and data rates may apply. Text STOP to cancel or HELP for help. Consent is not a condition of purchase. SMS opt-in is optional and is not required to submit your request.",
  },
  processing: { title: "Setting up your callback", items: { match: "Matching you with a vetted Arizona specialist", confirm: "Confirming a pro covers {city}", reserve: "Reserving your 2-minute callback" }, foot: "Finding pros near you in the Valley" },
  ty: {
    qualify: "Good news, your roof likely qualifies", youreIn: "You're in",
    h: "We'll call you within the next 2 minutes.", callfrom: "From {phone}. Keep your phone close.", ringLabel: "until we call",
    expiredH: "Our team may be on another call. Go ahead and call us now.", callNow: "Call us now",
    narrEyebrow: "A small, vetted network",
    narr1: "Here is the thing. We run a small, vetted network of Arizona's best home-service pros, and we are picky about who we let in, on both sides. We only send our pros customers who keep their appointments and treat them well, and in return, our homeowners get deals you won't find advertised anywhere.",
    narr2: "While we have you on the line, want us to cover anything else? Tap anything below and we will bring the best offer to your call.",
    narr2strong: "Tap anything below and we will bring the best offer to your call.",
    wallHeadOwner: "While we have you", wallHeadRenter: "Available where you rent", tapToAdd: "Tap to add",
    toggleAdd: "I'd like to learn about this", toggleAdded: "Added",
    ctaZero: "Confirm my 2-minute call", ctaN: "Discuss these {n} offers on our call", skip: "Just the roof for now",
    emailPlaceholder: "you@email.com", emailBtn: "Email me offers", emailDone: "Done. Watch your inbox.",
    emailStepH: "Your request is in. Want our seasonal Arizona offers by email too?", emailStepSub: "Your roof request is already submitted. This is just a bonus.", emailSkip: "Skip",
    offersOwner: {
      solar: { eyebrow: "Slash your APS/SRP bill up to 90%", head: "$0-Down Solar", benefit: "Nothing out of pocket to start." },
      windows: { eyebrow: "New windows, often $0 out of pocket", head: "Insurance-Covered Windows", benefit: "Energy-efficient, often covered by insurance." },
      hvac: { eyebrow: "Beat the Arizona heat before it spikes", head: "AC Tune-Up & Replacement", benefit: "Free AC health check before summer peaks." },
      pest: { eyebrow: "Keep scorpions out for good", head: "Scorpion & Pest Control", benefit: "Special homeowner rate." },
      gutters: { eyebrow: "Monsoon-proof your home", head: "Seamless Gutters", benefit: "Seamless gutters and leaf guards." },
      landscape: { eyebrow: "Cut your water bill, lose the upkeep", head: "Low-Water Desert Landscaping", benefit: "Water-smart makeover and artificial turf." },
      windowcleaning: { eyebrow: "Spotless glass, no ladder required", head: "Pro Window Cleaning", benefit: "One-time or recurring." },
    },
    offersRenter: {
      pest: { eyebrow: "Keep scorpions out for good", head: "Scorpion & Pest Control", benefit: "Renter-friendly plans." },
      alarms: { eyebrow: "Protection that moves with you", head: "Home Security & Monitoring", benefit: "No-drill smart alarm." },
      hvac: { eyebrow: "Stay cool through the summer peak", head: "AC Tune-Up", benefit: "Free AC health check." },
      windowcleaning: { eyebrow: "Spotless glass, no ladder required", head: "Pro Window Cleaning", benefit: "One-time or recurring." },
      housecleaning: { eyebrow: "Come home to a reset place", head: "House Cleaning", benefit: "Recurring or one-time cleanings." },
      plumbing: { eyebrow: "Fix leaks before they become headaches", head: "Plumbing Help", benefit: "Fast scheduling for common fixes." },
    },
  },
  confirmed: { h: "All set. Talk soon.", bodyA: "Your specialist has your roof request", bodyPlus: "plus {n} more {svc} to cover", svc1: "service", svcN: "services", bodyB: "Watch for a call from {phone}.", restart: "Start over",
    nextH: "What happens next", next: ["Talk to a real home-service concierge", "Lock in your roof appointment", "See which exclusive offers you qualify for"],
    saveH: "Save our number so you never miss a deal.", saveSub: "Add us to your contacts and we'll text you the seasonal Arizona offers our network gets first.", saveBtn: "Save our number" },
};
