/* strings-home-en.jsx — homepage copy (augments STRINGS.en.home) */
window.STRINGS = window.STRINGS || {}; window.STRINGS.en = window.STRINGS.en || {};
window.STRINGS.en.home = {
  nav: { services: "Services", howWeVet: "How we vet", areas: "Service areas", reviews: "Reviews", about: "About", contact: "Contact", quote: "Get a free quote", forPros: "For pros" },
  hero: {
    eyebrow: "Arizona's vetted home pros",
    pill: "Now serving the Greater Phoenix Valley — and expanding fast.",
    h: "One trusted contact for the whole house.",
    sub: "We match you with screened local pros and the exclusive deals our network gets first. No auctioning your info. No spam. Ever.",
    ctaPrimary: "Find your service", ctaSecondary: "Get the deals list",
  },
  servicesH: "What does your home need?",
  servicesSub: "Pick a service. We match you with a vetted Arizona pro who does exactly that work.",
  liveBadge: "Free quote", soonBadge: "Join the list",
  getStarted: "Get started",
  moreH: "More home services",
  moreShow: "Show all services", moreHide: "Show fewer",
  services: [
    { id: "roofing", icon: "ph-house-line", eyebrow: "Free quote in about 2 minutes", name: "Roofing", desc: "Repair, replace, or a free inspection. Tile, foam, shingle.", page: "Roofing.html" },
    { id: "solar", icon: "ph-sun", eyebrow: "Slash your power bill up to 90%", name: "Solar", desc: "$0-down options. Pay monthly, own your power.", page: "/solar" },
    { id: "ac", icon: "ph-wind", eyebrow: "Beat the Arizona heat", name: "AC & HVAC", desc: "Tune-ups, repair, and replacement before the peak.", page: "/ac-hvac" },
    { id: "windows", icon: "ph-grid-nine", eyebrow: "Often $0 with your coverage", name: "Windows", desc: "Energy-efficient windows, often insurance-covered.", page: "/windows" },
    { id: "bathroom", icon: "ph-bathtub", eyebrow: "Spa-style upgrades, fast", name: "Bathroom Remodel", desc: "Walk-in showers, tubs, vanities, and tile.", page: "/bathroom-remodel" },
    { id: "kitchen", icon: "ph-cooking-pot", eyebrow: "Cook in a kitchen you love", name: "Kitchen Remodel", desc: "Cabinets, counters, and full renovations.", page: "/kitchen-remodel" },
    { id: "pool", icon: "ph-swimming-pool", eyebrow: "Your backyard, beat the heat", name: "Pool", desc: "New builds, remodels, and resurfacing.", page: "/pool" },
    { id: "pest", icon: "ph-bug-beetle", eyebrow: "Keep scorpions out for good", name: "Pest & Scorpion Control", desc: "Plans for homeowners and renters.", page: "/pest-control" },
  ],
  moreServices: [
    { id: "gutters", icon: "ph-cloud-rain", name: "Gutters", page: "/gutters" },
    { id: "siding", icon: "ph-house-simple", name: "Siding", page: "/siding" },
    { id: "garage-doors", icon: "ph-door", name: "Garage Doors", page: "/garage-doors" },
    { id: "foundation", icon: "ph-stack", name: "Foundation Repair", page: "/foundation-repair" },
    { id: "insulation", icon: "ph-thermometer", name: "Insulation", page: "/insulation" },
    { id: "pool-service", icon: "ph-drop", name: "Pool Service", page: "/pool-service" },
    { id: "landscape", icon: "ph-plant", name: "Desert Landscaping", page: "/desert-landscaping" },
    { id: "tree", icon: "ph-tree", name: "Tree Service", page: "/tree-service" },
    { id: "plumbing", icon: "ph-wrench", name: "Plumbing", page: "/plumbing" },
    { id: "electrical", icon: "ph-lightning", name: "Electrical", page: "/electrical" },
    { id: "water", icon: "ph-flask", name: "Water Treatment", page: "/water-treatment" },
    { id: "security", icon: "ph-shield-check", name: "Home Security", page: "/home-security" },
    { id: "flooring", icon: "ph-squares-four", name: "Flooring", page: "/flooring" },
    { id: "painting", icon: "ph-paint-roller", name: "Painting", page: "/painting" },
    { id: "epoxy", icon: "ph-paint-bucket", name: "Garage Epoxy", page: "/garage-epoxy" },
    { id: "cleaning", icon: "ph-broom", name: "House Cleaning", page: "/house-cleaning" },
    { id: "windowcln", icon: "ph-sparkle", name: "Window Cleaning", page: "/window-cleaning" },
  ],
  how: {
    eyebrow: "How it works",
    h: "A concierge for your whole home.",
    steps: [
      { icon: "ph-house", head: "Tell us what your home needs", body: "Roofing today, whatever comes next. A few quick taps." },
      { icon: "ph-users-three", head: "We match you with a vetted local pro", body: "A small network we screen on license, insurance, and track record." },
      { icon: "ph-phone-call", head: "One real contact. Free quote. No spam.", body: "You talk to us, and only the pros you ask for." },
    ],
  },
  areas: {
    eyebrow: "Local to the Valley",
    h: "Now serving the Greater Phoenix Valley — and expanding fast.",
    sub: "Crews who know Arizona roofs, Arizona heat, and Arizona monsoons.",
    cities: ["Phoenix", "Mesa", "Gilbert", "Chandler", "Scottsdale", "Tempe", "Glendale", "Peoria", "Surprise"],
  },
  deals: {
    eyebrow: "Exclusive deals",
    h: "Get the deals our network sees first.",
    sub: "Seasonal Arizona offers we keep off the public market, sent only to our homeowners. No spam, unsubscribe anytime.",
    emailPlaceholder: "you@email.com", btn: "Join the deals list",
    sms: "Text me the best deals too. Standard rates may apply, reply STOP to opt out.",
    done: "You're on the list. Watch your inbox for Arizona's best deals.",
    save: "Or save our number",
  },
  about: {
    eyebrow: "Why we started this",
    h: "We were tired of the lead farms too.",
    body: "Vetted Local Providers is a small Arizona team that got fed up watching neighbors get their numbers auctioned to twenty strangers. So we built the opposite: a vetted network, one real contact, and deals you earn by being easy to work with.",
    cta: "Read our story",
  },
  faq: {
    eyebrow: "Questions",
    h: "Good questions, straight answers.",
    items: [
      { q: "Are you the contractor?", a: "No. We are a referral service that matches you with licensed, ROC-registered Arizona pros. We are not a licensed contractor ourselves." },
      { q: "Will my phone blow up with spam?", a: "No. We never auction your number. You talk to us, and only the pros you ask for." },
      { q: "What does it cost?", a: "Nothing to get matched and quoted. Quotes are free and no-obligation." },
      { q: "What areas do you cover?", a: "The Greater Phoenix Valley, from Surprise to Gilbert and everywhere between." },
    ],
    cta: "See all FAQs",
  },
  footer: {
    tagline: "Your Arizona home-service concierge. One trusted contact for the whole house.",
    company: "Company", servicesCol: "Services", areasCol: "Service areas", legal: "Legal",
    links: {
      about: "About", howWeVet: "How we vet", contact: "Contact", reviews: "Reviews", faq: "FAQ", blog: "Blog",
      privacy: "Privacy Policy", terms: "Terms", tcpa: "TCPA & consent", cookies: "Cookie Policy", accessibility: "Accessibility", guarantee: "Our Guarantee",
    },
    roc: "We only work with licensed, ROC-registered Arizona pros.",
    addr: "Greater Phoenix Valley, Arizona",
    fine: "We are a referral service, not a licensed contractor. We never sell or spam your information. © 2026 Vetted Local Providers.",
    contact: "hello@vettedlocalproviders.com",
    disclaimerNote: "Placeholder language, pending attorney review.",
    disclaimer: "Vetted Local Providers is a lead-referral service that connects Arizona homeowners with independent, licensed, ROC-registered service providers. We are not a licensed contractor and do not perform home-improvement work ourselves. We are not affiliated with, endorsed by, or sponsored by Meta Platforms, Inc. (Facebook, Instagram), Google, or any other platform. All trademarks are the property of their respective owners. We do not sell your personal information to third parties; we connect you only with the providers you request. Savings, offers, and results vary and are not guaranteed. By submitting a request you agree to our Privacy Policy, Terms of Service, and to be contacted as described in our consent terms. © 2026 Vetted Local Providers. All rights reserved.",
    disclaimerShort: "Vetted Local Providers is a lead-referral service connecting Arizona homeowners with independent, licensed, ROC-registered providers. We are not a licensed contractor and are not affiliated with or endorsed by Meta, Google, or any other platform. All trademarks belong to their respective owners. We do not sell your personal information. Offers and results vary and are not guaranteed. © 2026 Vetted Local Providers. All rights reserved.",
  },
};
